### PR TITLE
Add nested NSArray/NSSet/NSDictionary support

### PR DESCRIPTION
**Pull request by kukat**

### CODE REVIEW

**Comment by siuying** [comment]
Thanks! Can you also add test cases for them, so that I'd know how to use them?

I have fixed a bug in the test, please pull this change before adding it: https://github.com/siuying/IGSignature/commit/b832940f3802c14fe4b75245badf140fe28e8f4e

**Comment by siuying** [comment]
Any reason to sort the array? @[@"1", @"2"] should not be equal to @[@"2", @"1"] to me.

**Comment by kukat** [comment]
Thanks for quick response, according to server side signature packages, the params should be sorted by the keys
https://github.com/mloughran/signature/blob/master/lib/signature.rb#L189
https://github.com/philipbrown/signature-php/blob/master/src/Request.php#L77

**Comment by siuying** [comment]
Thanks for the clear up! Can you help adding the test case?

**Pull request closed without merging**
